import { MODEL_REGISTRY } from "../../domain/models.js";
import { calculateCost } from "../../domain/pricing.js";
import prompts from "../../prompts.json" with { type: "json" };

/**
 * Removes AI usage metadata and the Triage section generated by the planner.
 * @param {string} text
 * @returns {string}
 */
export function removePlannerMetadata(text) {
  if (!text) return "";
  let cleanText = text.replace(/<!-- ai-usage:.*?-->/gi, "");

  // Explicit Marker Removal (Priority)
  if (cleanText.includes("<!-- ai-triage-start -->")) {
    cleanText = cleanText.replace(/<!-- ai-triage-start -->[\s\S]*?<!-- ai-triage-end -->/gi, "");
  } else {
    // Robust fallback: remove common triage headers until any recognized plan header
    const planHeaders = [
      "### 🎯 Plan",
      "### Plan",
      "### Approach",
      "### Technical",
      "### Planning",
      "#### Approach",
      "### 🔍 AI Architecture Review",
      "### Review",
    ];
    const planHeaderRegex = new RegExp(`(?=${planHeaders.join("|")})`, "i");

    cleanText = cleanText.replace(/### (📋 )?Triage[\s\S]*?/gi, (match) => {
      const parts = match.split(planHeaderRegex);
      if (parts.length > 1) {
        return parts.slice(1).join("");
      }
      // If no plan header found, it might just be a triage report.
      // We still want to remove the triage section but keep the rest if any.
      // For now, if it starts with triage and has nothing else recognized, we return empty
      // but only if it's clearly a triage report (has specific markers or keywords)
      return match.includes("type:") || match.includes("priority:") ? "" : match;
    });
  }

  return cleanText.trim();
}

/**
 * AI Planner logic to read a GitHub Issue and post a technical plan.
 */
export async function planIssue({
  gitProvider,
  owner,
  repo,

  issueNumber,
  issueTitle,
  issueBody,
  aiProvider,
  model,
  availableProviders = [], // List of providers with available API keys
  customSystemPrompt,
  customUserPrompt,
  maxInputTokens = 200000,
  maxOutputTokens = 200000,
  onStart = (_args) => {},
  onStatus = (_args) => {},
}) {
  const system = customSystemPrompt || prompts.planner.system;
  const userTemplate = customUserPrompt || prompts.planner.userTemplate;

  const modelContext = Object.entries(MODEL_REGISTRY)
    .filter(
      ([_, entry]) =>
        !entry.deprecated &&
        entry.provider !== "mock" &&
        availableProviders.includes(entry.provider),
    )
    .map(
      ([name, entry]) =>
        `- **${name}**: ${entry.description} (Input: $${entry.pricing.input}/1M, Output: $${entry.pricing.output}/1M)`,
    )
    .join("\n");

  const systemPrompt = system.replace("{{repo}}", repo).replace("{{model_registry}}", modelContext);

  let userPrompt = userTemplate.replace("{{title}}", issueTitle).replace("{{body}}", issueBody);

  // Ensure AI follows the response structure with markers
  if (prompts.planner.responseTemplate) {
    userPrompt += `\n\n### RESPONSE STRUCTURE (STRICT):\n${prompts.planner.responseTemplate}`;
  }

  onStart({ systemPrompt, userPrompt });

  // Input Safety Check (Estimated tokens: char count / 4)
  const estimatedInputTokens = Math.ceil((systemPrompt.length + userPrompt.length) / 4);
  if (estimatedInputTokens > maxInputTokens) {
    return {
      success: false,
      error: `Input context too large: ${estimatedInputTokens} tokens (limit: ${maxInputTokens}). Please reduce the issue description or custom prompts.`,
    };
  }

  const generatedResponse = await aiProvider.generateContent(
    model,
    systemPrompt,
    userPrompt,
    maxOutputTokens,
  );

  const plan = generatedResponse.text;
  const usage = generatedResponse.usage;

  // Simulated Blocker Detection logic (Triage)
  const blockerMatch = issueBody.match(/(?:depends on|blocked by) #(\d+)/i);
  const blockers = blockerMatch ? [parseInt(blockerMatch[1])] : [];

  const costs = calculateCost(model, usage);

  // Surgical Context Cleaning: Ensure triage part is correctly prioritized for removal
  let planWithMarkers = plan;
  if (!plan.includes("<!-- ai-triage-start -->")) {
    // If AI forgot markers, try to wrap the Triage section manually to aid future context building
    planWithMarkers = plan.replace(/(### (📋 )?Triage)/i, "<!-- ai-triage-start -->\n$1");
    if (planWithMarkers !== plan && !planWithMarkers.includes("<!-- ai-triage-end -->")) {
      planWithMarkers = planWithMarkers.replace(
        /(### (🎯 )?Plan Overview)/i,
        "<!-- ai-triage-end -->\n\n$1",
      );
    }
  }

  await gitProvider.createComment(
    owner,
    repo,
    issueNumber,
    `<!-- ai-usage: ${JSON.stringify(usage)} -->\n${planWithMarkers}${
      blockers.length > 0
        ? `\n\n⚠️ **Blockers Detected**: This issue depends on #${blockers.join(", #")}`
        : ""
    }`,
  );

  // Apply Triage Actions (Labels & Milestone)
  onStatus({ type: "triage", message: "APPLYING TRIAGE ACTIONS..." });
  const priority =
    issueBody.toLowerCase().includes("urgent") || issueBody.toLowerCase().includes("bug")
      ? "priority: critical"
      : "priority: standard";
  const labels = ["type: task", priority];

  // Smart Milestone Selection: Milestone 1 for critical, 2 for others
  const milestone = priority === "priority: critical" ? 1 : 2;

  if (blockers.length > 0) {
    onStatus({
      type: "blockers",
      message: `Setting up blocking relationships for issues: ${blockers.join(", ")}`,
    });
    for (const blockerId of blockers) {
      onStatus({
        type: "api_call",
        message: `[API CALL] POST repos/${owner}/{repo}/issues/${issueNumber}/dependencies { blocked_by_issue_number: ${blockerId} }`,
      });
    }
  }

  onStatus({
    type: "labels",
    message: `Applying labels: ${labels.join(", ")}`,
  });
  onStatus({
    type: "milestone",
    message: `Assigning to Milestone #${milestone}`,
  });

  await gitProvider.addLabels(owner, repo, issueNumber, labels);
  await gitProvider.updateMilestone(owner, repo, issueNumber, milestone);

  return {
    success: true,
    value: {
      plan,
      systemPrompt,
      userPrompt,
      usage,
      triage: { labels, milestone, blockers },
      costs,
    },
  };
}
