import fs from "node:fs";
import path from "node:path";
import { branding } from "../../domain/branding.js";
import { MODEL_REGISTRY } from "../../domain/models.js";
import { calculateCost } from "../../domain/pricing.js";
import prompts from "../../prompts.json" with { type: "json" };

/**
 * Removes AI usage metadata and the Triage section generated by the planner.
 * @param {string} text
 * @returns {{ success: boolean, value: string, error?: string }}
 */
export function removePlannerMetadata(text) {
  if (!text) return { success: true, value: "" };
  let cleanText = text.replace(/<!-- ai-usage:.*?-->/gi, "");

  // Explicit Marker Removal (Priority)
  if (cleanText.includes("<!-- ai-triage-start -->")) {
    cleanText = cleanText.replace(/<!-- ai-triage-start -->[\s\S]*?<!-- ai-triage-end -->/gi, "");
  } else {
    // Robust fallback: remove common triage headers until any recognized plan header
    const planHeaders = [
      "### 🎯 Plan",
      "### Plan",
      "### Approach",
      "### Technical",
      "### Planning",
      "#### Approach",
      "### 🔍 AI Architecture Review",
      "### Review",
    ];
    const planHeaderRegex = new RegExp(`(?=${planHeaders.join("|")})`, "i");

    cleanText = cleanText.replace(/### (📋 )?Triage[\s\S]*?/gi, (match) => {
      const parts = match.split(planHeaderRegex);
      if (parts.length > 1) {
        return parts.slice(1).join("");
      }
      // If no plan header found, it might just be a triage report.
      // We still want to remove the triage section but keep the rest if any.
      // For now, if it starts with triage and has nothing else recognized, we return empty
      // but only if it's clearly a triage report (has specific markers or keywords)
      return match.includes("type:") || match.includes("priority:") ? "" : match;
    });
  }

  return { success: true, value: cleanText.trim() };
}

/**
 * Parses the AI plan and creates native GitHub sub-issues.
 */
async function decomposePlanIntoSubIssues(gitProvider, { owner, repo, parentIssueNumber, plan }) {
  // Extract the Technical Checklist section
  const checklistSectionMatch = plan.match(
    /### 🛠️ Technical Checklist([\s\S]*?)(?=If approved|###|$)/i,
  );
  if (!checklistSectionMatch) return [];

  const checklistText = checklistSectionMatch[1];

  // Split by checklist items "- [ ]" but keep the delimiters to extract blocks
  const taskBlocks = checklistText.split(/- \[ \] /g).slice(1);

  if (taskBlocks.length === 0) return [];

  // Extract shared context for all sub-tasks
  let sharedContext = "";
  const overviewMatch = plan.match(/### 🎯 Plan Overview([\s\S]*?)(?=###|If approved)/i);
  if (overviewMatch?.[1]?.trim()) {
    sharedContext += `### 🎯 Plan Overview\n${overviewMatch[1].trim()}\n\n`;
  }

  const scopeMatch = plan.match(/### Scope([\s\S]*?)(?=###|If approved)/i);
  if (scopeMatch?.[1]?.trim()) {
    sharedContext += `### Scope\n${scopeMatch[1].trim()}\n\n`;
  }

  const subIssues = [];
  for (const block of taskBlocks) {
    const lines = block.trim().split("\n");
    const title = lines[0].replace(/^(?:Task \d+: )?/i, "").trim();
    const detailedBody = lines.slice(1).join("\n").trim();

    const body = `Sub-task of #${parentIssueNumber}\n\n${sharedContext}${
      detailedBody ? `### 📝 Details\n${detailedBody}\n\n` : ""
    }--- \n${branding.getSignature()}`;

    try {
      const subIssue = await gitProvider.createIssue(owner, repo, {
        title,
        body,
        labels: ["type: sub-task"],
      });

      await gitProvider.addSubIssue(owner, repo, parentIssueNumber, subIssue.id);
      subIssues.push({ number: subIssue.number, title });
    } catch (err) {
      console.error(`Failed to create sub-issue "${title}": ${err.message}`);
    }
  }
  return subIssues;
}

/**
 * AI Planner logic to read a GitHub Issue and post a technical plan.
 */
export async function planIssue({
  gitProvider,
  owner,
  repo,

  issueNumber,
  issueTitle,
  issueBody,
  aiProvider,
  model,
  availableProviders = [], // List of providers with available API keys
  customSystemPrompt,
  customUserPrompt,
  maxInputTokens = 200000,
  maxOutputTokens = 200000,
  onStart = (_args) => {},
  onStatus = (_args) => {},
}) {
  const system = customSystemPrompt || prompts.planner.system;
  const userTemplate = customUserPrompt || prompts.planner.userTemplate;

  const modelContext = Object.entries(MODEL_REGISTRY)
    .filter(
      ([_, entry]) =>
        !entry.deprecated &&
        entry.provider !== "mock" &&
        availableProviders.includes(entry.provider),
    )
    .map(
      ([name, entry]) =>
        `- **${name}**: ${entry.description} (Input: $${entry.pricing.input}/1M, Output: $${entry.pricing.output}/1M)`,
    )
    .join("\n");

  // Rule Discovery
  let projectRules = "Follow standard Clean Architecture and project conventions.";
  const rulePaths = [
    ".agent/RULES.md",
    "RULES.md",
    "GEMINI.md",
    ".serena/memories/serena-workflow.md",
  ];
  for (const rulePath of rulePaths) {
    const fullPath = path.resolve(process.cwd(), rulePath);
    if (fs.existsSync(fullPath)) {
      projectRules = fs.readFileSync(fullPath, "utf-8");
      break;
    }
  }

  // RECURSION GUARD: If it's already a sub-task, don't decompose further unless triaged as spike/split
  if (issueBody.includes(`Sub-task of #`)) {
    const isDecompositionRequested =
      issueBody.toLowerCase().includes("spike") || issueBody.toLowerCase().includes("split");
    if (!isDecompositionRequested) {
      onStatus({
        type: "guard",
        message: "Detected sub-task. Skipping redundant decomposition to prevent infinite loops.",
      });
      // Still need to perform triage actions
    }
  }

  const systemPrompt = system
    .replace("{{repo}}", repo)
    .replace("{{model_registry}}", modelContext)
    .replace("{{project_rules}}", projectRules);

  let userPrompt = userTemplate.replace("{{title}}", issueTitle).replace("{{body}}", issueBody);

  // Ensure AI follows the response structure with markers
  if (prompts.planner.responseTemplate) {
    userPrompt += `\n\n### RESPONSE STRUCTURE (STRICT):\n${prompts.planner.responseTemplate}`;
  }

  onStart({ systemPrompt, userPrompt });

  // Input Safety Check (Estimated tokens: char count / 4)
  const estimatedInputTokens = Math.ceil((systemPrompt.length + userPrompt.length) / 4);
  if (estimatedInputTokens > maxInputTokens) {
    return {
      success: false,
      error: `Input context too large: ${estimatedInputTokens} tokens (limit: ${maxInputTokens}). Please reduce the issue description or custom prompts.`,
    };
  }

  const generatedResponse = await aiProvider.generateContent(
    model,
    systemPrompt,
    userPrompt,
    maxOutputTokens,
  );

  const plan = generatedResponse.text;
  const usage = generatedResponse.usage;

  // Simulated Blocker Detection logic (Triage)
  const blockerMatch = issueBody.match(/(?:depends on|blocked by) #(\d+)/i);
  const blockers = blockerMatch ? [parseInt(blockerMatch[1], 10)] : [];

  const costResult = calculateCost(model, usage);
  const costs = costResult.value;

  // Surgical Context Cleaning: Ensure triage part is correctly prioritized for removal
  let planWithMarkers = plan;
  if (!plan.includes("<!-- ai-triage-start -->")) {
    // If AI forgot markers, try to wrap the Triage section manually to aid future context building
    planWithMarkers = plan.replace(/(### (📋 )?Triage)/i, "<!-- ai-triage-start -->\n$1");
    if (planWithMarkers !== plan && !planWithMarkers.includes("<!-- ai-triage-end -->")) {
      planWithMarkers = planWithMarkers.replace(
        /(### (🎯 )?Plan Overview)/i,
        "<!-- ai-triage-end -->\n\n$1",
      );
    }
  }

  await gitProvider.createComment(
    owner,
    repo,
    issueNumber,
    `<!-- ai-usage: ${JSON.stringify(usage)} -->\n${planWithMarkers}${
      blockers.length > 0
        ? `\n\n⚠️ **Blockers Detected**: This issue depends on #${blockers.join(", #")}`
        : ""
    }`,
  );

  // Decompose into sub-issues
  onStatus({
    type: "decomposition",
    message: "DECOMPOSING PLAN INTO SUB-TASKS...",
  });
  const subIssues = await decomposePlanIntoSubIssues(gitProvider, {
    owner,
    repo,
    parentIssueNumber: issueNumber,
    plan,
  });

  if (subIssues.length > 0) {
    const subIssueList = subIssues.map((s) => `#${s.number}`).join(", ");
    onStatus({
      type: "decomposition",
      message: `Created ${subIssues.length} sub-tasks: ${subIssueList}`,
    });
  }

  // Apply Triage Actions (Labels & Milestone)
  onStatus({ type: "triage", message: "APPLYING TRIAGE ACTIONS..." });
  const priority =
    issueBody.toLowerCase().includes("urgent") || issueBody.toLowerCase().includes("bug")
      ? "priority: critical"
      : "priority: standard";
  const labels = ["type: task", priority];

  // Smart Milestone Selection: Milestone 1 for critical, 2 for others
  const milestone = priority === "priority: critical" ? 1 : 2;

  if (blockers.length > 0) {
    onStatus({
      type: "blockers",
      message: `Setting up blocking relationships for issues: ${blockers.join(", ")}`,
    });
    for (const blockerId of blockers) {
      onStatus({
        type: "api_call",
        message: `[API CALL] POST repos/${owner}/{repo}/issues/${issueNumber}/dependencies { blocked_by_issue_number: ${blockerId} }`,
      });
    }
  }

  onStatus({
    type: "labels",
    message: `Applying labels: ${labels.join(", ")}`,
  });
  onStatus({
    type: "milestone",
    message: `Assigning to Milestone #${milestone}`,
  });

  await gitProvider.addLabels(owner, repo, issueNumber, labels);
  await gitProvider.updateMilestone(owner, repo, issueNumber, milestone);

  return {
    success: true,
    value: {
      plan,
      systemPrompt,
      userPrompt,
      usage,
      triage: { labels, milestone, blockers },
      costs,
    },
  };
}
