[[rule]]
toolName = "network"
decision = "ask_user"
priority = 1000
argsPattern = "\"strategy\\\""

[[rule]]
toolName = "files"
decision = "allow"
priority = 1
argsPattern = "\"strategy\\\""

[[rule]]
toolName = "tools"
decision = "allow"
priority = 1
argsPattern = "\"strategy\\\""
