/**
 * Checks if a given text body is an AI-generated report that should be excluded from context.
 *
 * @param {string} body - The text to check.
 * @returns {boolean} True if the text is an AI report.
 */
export function isAIReport(body) {
  if (!body) return false;

  return (
    /### (📋 )?Triage/i.test(body) ||
    /### (🎯 )?Plan/i.test(body) ||
    /### (🛠️ )?Technical Checklist/i.test(body) ||
    /AI Triage & Planning Report/i.test(body) ||
    /ai-triage-(start|end)/i.test(body) ||
    /--- AI SIMULATION/i.test(body) ||
    /🔍 AI Architecture Review/i.test(body) ||
    /Review generated by AI Orchestration/i.test(body) ||
    /<!-- ai-usage:.*?-->/i.test(body)
  );
}
