/**
 * Unified Branding for the AI Orchestrator.
 * Represents the identity of the agent.
 */
export const branding = {
  name: "AI", // Default
  setName(newName) {
    if (newName) this.name = newName;
  },
  getSignature: () => `Generated by ${branding.name} Orchestrator.`,
};
